sudo: false
language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.1
  - 18.0
install: "true"
branches:
  only:
    - master
    - develop
script: "make test dialyzer"
cache:
  directories:
  - _plt
  - $HOME/.mix/archives
notifications:
  email:
    - priestjim@gmail.com

