sudo: false
language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.1
  - 18.0
install: "true"
branches:
  only:
    - master
script: "make test dialyzer"
notifications:
  email:
    - priestjim@gmail.com

