sudo: false
language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.0
install: "true"
branches:
  only:
    - master
    - develop
script: "make test dialyzer"
after_success:
  - mix do compile, coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
cache:
  directories:
  - _plt
  - $HOME/.mix/archives
notifications:
  email:
    - priestjim@gmail.com
